project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Zipeng MA"
  site-url: https://zipengmarkma.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/ZipengMarkMA
  repo-actions: [edit, issue]
  
  page-footer: |
    <div class="footer-text">
    <div>Zipeng MA</div>
    <div><a href="mailto:zipeng.ma@essec.edu">zipeng.ma@essec.edu</a></div>
    <div>Office 5M5, Economics Department, ESSEC Business School, Singapore</div>
    </div>
    
  navbar: 
    background: "#A9CCE3"
    search: false
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Papers"
        href: Papers.qmd
      - text: "CV"
        href: ZipengMACV.md
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细